# Generated by Django 3.1.2 on 2020-11-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foodMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField(null=True)),
                ('price', models.FloatField()),
                ('ratings', models.FloatField(default=0.0)),
                ('foodtype', models.CharField(max_length=20)),
                ('rest', models.CharField(default='', max_length=100)),
                ('onTrend', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='res_pics')),
                ('desc', models.TextField(default='')),
                ('ratings', models.FloatField(default=0.0)),
                ('opens', models.TextField()),
                ('foodtypes', models.TextField()),
                ('location', models.TextField(default='')),
                ('contact', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
