# Generated by Django 3.1.2 on 2020-11-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='slug',
            field=models.SlugField(default='rest '),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(default='rest '),
        ),
    ]
